CREATE TABLE goals (
    id    BIGSERIAL PRIMARY KEY,
    title varchar(255)
);
	GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO db_user_planning;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO db_user_planning;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO db_user_planning;
	ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO db_user_planning;